packages:
  - packages/*
  - examples/*
  - playground

catalog:
  '@oxc-project/runtime': 0.112.0
  '@standard-schema/spec': 1.1.0
  c12: 3.3.3
  consola: 3.4.2
  defu: 6.1.4
  pathe: 2.0.3
  rolldown: 1.0.0-rc.3
  srvx: 0.11.0
  zod: 4.3.6

ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - protobufjs
  - re2
  - serverless

onlyBuiltDependencies:
  - nx
  - simple-git-hooks
