import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';
import type { Plugin } from 'vite';

const here = dirname(fileURLToPath(import.meta.url));
const generated = resolve(here, '../src/Generated/UI.ts');

function emitSingleFile(): Plugin {
  return {
    name: 'vercube-devtools:single-file',
    enforce: 'post',
    generateBundle(_options, bundle) {
      let html = '';
      const scripts: string[] = [];
      const styles: string[] = [];

      for (const [fileName, chunk] of Object.entries(bundle)) {
        if (chunk.type === 'chunk' && fileName.endsWith('.js')) {
          scripts.push(chunk.code);
          delete bundle[fileName];
          continue;
        }

        if (chunk.type === 'asset' && fileName.endsWith('.css')) {
          styles.push(String(chunk.source));
          delete bundle[fileName];
          continue;
        }

        if (chunk.type === 'asset' && fileName.endsWith('.html')) {
          html = String(chunk.source);
          delete bundle[fileName];
        }
      }

      html = html
        .replaceAll(/<script[^>]*\ssrc="[^"]*"[^>]*><\/script>/g, '')
        .replaceAll(/<link[^>]*\srel="stylesheet"[^>]*>/g, '')
        .replaceAll(/<link[^>]*\srel="modulepreload"[^>]*>/g, '');

      const css = styles.join('\n');
      const js = scripts.join('\n');

      // A closing tag inside the code would end the <script> element early.
      if (js.includes('</script')) {
        this.error('Bundled devtools UI contains a literal </script sequence and cannot be inlined.');
      }

      const inlined = html
        .replace('</head>', () => `<style>${css}</style></head>`)
        .replace('</body>', () => `<script type="module">${js}</script></body>`);

      const external = inlined.match(/(?:src|href)="(?!data:|#)[^"]*"/g);

      if (external) {
        this.error(`Devtools UI references assets it cannot load: ${external.join(', ')}`);
      }

      const module = [
        '/* eslint-disable */',
        '// Generated by `pnpm --filter @vercube/devtools build:ui`. Do not edit by hand.',
        '',
        '',
        `export const DEVTOOLS_UI_HTML: string = ${JSON.stringify(inlined)};`,
        '',
      ].join('\n');

      writeFileSync(generated, module, 'utf8');
      this.warn(`devtools UI written to src/Generated/UI.ts (${(inlined.length / 1024).toFixed(1)} kB)`);
    },
  };
}

const proxyTarget = process.env.VERCUBE_DEVTOOLS_TARGET ?? 'http://localhost:3000';

export default defineConfig({
  root: here,
  base: './',
  plugins: [vue(), emitSingleFile()],
  server: {
    proxy: {
      '/_devtools/api': { target: proxyTarget, changeOrigin: true },
    },
  },
  build: {
    outDir: resolve(here, 'dist'),
    emptyOutDir: true,
    cssCodeSplit: false,
    modulePreload: { polyfill: false },
    reportCompressedSize: false,
    assetsInlineLimit: 256 * 1024,
    rollupOptions: {
      input: resolve(here, 'index.html'),
      output: { inlineDynamicImports: true, entryFileNames: 'app.js', assetFileNames: 'app.[ext]' },
    },
  },
  define: {
    __VUE_OPTIONS_API__: 'false',
    __VUE_PROD_DEVTOOLS__: 'false',
    __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: 'false',
  },
});
