name: Unit Test

permissions: {}

on:
  push:
    branches: [main, v1]
  pull_request:
    branches: [main, v1]

jobs:
  unit-test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1
    with:
      os-matrix: '"ubuntu-slim"'
      node-versions: '24'
      build-for-lint: true
      typecheck: pnpm test:tscheck
      lint: pnpm test:lint

  release-commit:
    needs: [unit-test]
    if: github.event_name == 'pull_request'
    permissions: {}
    uses: sxzz/workflows/.github/workflows/release-commit.yml@v1
    with:
      build: pnpm build
      packages: "./packages/*"
      comment-package-manager: pnpm