name: Unit Test

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    uses: sxzz/workflows/.github/workflows/unit-test.yml@v1
    with:
      os-matrix: '"ubuntu-slim"'
      node-versions: '24'
      build-for-lint: true
      typecheck: pnpm test:tscheck
      lint: pnpm test:lint

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Approve PNPM Builds
        run: pnpm approve-builds --yes

      - name: Run Typecheck
        run: pnpm test:tscheck

      - name: Run Lint
        run: pnpm test:lint
